### ISSUE TITLE
Instructor feedback - erd

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [Celtic68/grbUniformOrdering#1]
Nice work Joe!    

1. I wonder about including both User and Player on the order table. I  understand the desire/need to easily get at all the user's orders, but you should be able to still get at it from the player table. What do you think?

2. Is there any need to capture a quantity for the various uniform pieces? Maybe that would overcomplicate things at this point? MVP.

3. user table - rather than the admin flag, we'll use a role table as you alluded to in your slack message. The role table will have: id, user_login_in, and role. Role is where you'll indicate admin or not.

**Comment by Celtic68** [comment]
1.  Great point - as long as I have the player, getting the user should be a snap.

2. Right now, there is not.  When someone wants extra pants (thats really the only piece that people tend to get more of), they order them outside of the meeting.  Most people tend to wait until closer to the season because boys tend to grow like sprouts in 5 months.  :)

3.  Right - should we be creating a role table right now or is that something we need to do as part of the class exercise?

**Comment by pawaitemadisoncollege** [comment]
1 and 2 sound good/make sense.

**Comment by Celtic68** [comment]
Great - thanks!!
